utils::globalVariables(
  c(
    "idx_start",
    "idx_end",
    "cycles_start",
    "cycles_end",
    "time",
    "cycle_number",
    "date_time",
    "Reference",
    "Prediction",
    "Freq",
    "rating",
    "stage_idx",
    "pred",
    "x",
    "y",
    "cost",
    "combinations_per_product",
    "lower_percentile",
    "upper_percentile"
  )
)
